### PR TITLE
Feature/cache adapters

### PR DESCRIPTION
**Pull request by KensoDev**
- Added adapters support
- CacheStore adapter
- RedisStrore adapter
- fragments are store in the Rails.cache of course, only the tags store is being changed
- refactored the main cachier specs to be only focused on the adapter communication 
- added specs for the redis store and for the cache store
- edited the README.

### CODE REVIEW

**Comment by ahawkins** [comment]
Hey man. Thanks a lot for this! 

It all looks pretty good to me.

The redis configuration (in the specs) is the only thing that looks a little weird to me. Is there a cleaner way to do that?

Instead of using `$redis` why not just the redis connection in a `config.before :suite` that way you never need to acces it. The $redis connection should never be manipulate directly in the tests.

Also, I don't think we need guard. I try to keep that stuff light on open source projects. 

Otherwise the main code & tests look :thumbsup:

**Comment by KensoDev** [comment]
@Adman65 I will move the redis to a before.
About Guard, I was completely sure I removed all trace of it :-), I will check what remained inside and I will remove it.

**Comment by KensoDev** [comment]
@Adman65 I don't see anything related to Guard anymore, I removed it completely.
You may see commit messages with it, but the DIFF has nothing Guard related.

**Comment by KensoDev** [comment]
@Adman65 refactored

**Pull request merged**
