### PR TITLE
Add key namespaces (or 'prefixes') to redis store

### PR DESCRIPTION
**Pull request by amoslanka**

### CODE REVIEW

**Comment by ahawkins** [comment]
Hmm, I'm on the fence about this one. I can see this being useful for the cache adapter. However redis-namespace does exactly the same thing without complicating the code. What do you think of simply making the cache adapter prepend "cashier" to all the keys? Another solution is to avoid prefixing in the adapter entirely and do it all inside the controller helper. What do you think of that?

**Comment by amoslanka** [comment]
(accidentally commited the adjustments to #clear to master branch before branching to namespaces. thats why the #clear adjustments are also in this PR)

**Comment by amoslanka** [comment]
I was unaware of the redis-namespace gem. Thats definitely the direction I'll take. Will reimplement, and hopefully it should work without adjusting the Cashier code at all. (Does Cashier currently play nice with a Redis::Namespace instance?)

I'm definitely against expecting a user to add prefixes to all tags. If a user needed a prefix, there would be a lot of redundancy in adding "cashier:<tag>" over and over for the tags in their application code. Namespacing should certainly be handled by the gem to avoid clutter in the app.

In terms of the cache store, it would essentially be the same implementation as I have for the redis store, minus the customizability, correct? I can't say whether it would be as necessary as the redis namespace seems to me to be. Though having all the cache keys stored as cashier/tag-name and cachier/tags would be more apt to avoid conflict. It seems to me that if a namespace is going to be implemented on one store, it should be available on the other. Thats something I didn't think as much about until after the pull request. And if any namespace is implemented, perhaps defaulting to "cashier", doesn't it make sense to be able to configure that prefix?

I'll work this through a bit and commit some more adjustments.

**Comment by ahawkins** [comment]
> I was unaware of the redis-namespace gem. Thats definitely the direction
> I'll take. Will reimplement, and hopefully it should work without adjusting
> the Cashier code at all. (Does Cashier currently play nice with a
> Redis::Namespace instance?)

Ya. Redis-namespace acts just like a normal redis instance.

Are you currently using the cache-store? I think most people are using
redis since it's much faster.

**Comment by amoslanka** [comment]
My application will be using Redis for Cashier, but for obvious reasons its worth finding a solution that will cover both stores.

**Comment by amoslanka** [comment]
@twinturbo, Any opinions on adding redis-namespace as a gem dependency vs. expecting any prefixing to happen when Cashier is being configured by the app using it?

**Comment by amoslanka** [comment]
@twinturbo, Any opinions on adding redis-namespace as a gem dependency vs. expecting any prefixing to happen when Cashier is being configured by the app using it? This would allow the abstract implementation of a `Cashier#key_prefix=` which would be delegated to the store. This would require cache_store to implement it in its keys.

Otherwise, I'm generally going to close this issue as in my projects I'm wrapping the redis instance passed into Cashier in the initializer.

**Comment by ahawkins** [comment]
@amoslanka tbh i'm thinking about removing the cache-store because it's entirely unperformant. The benchmarks are way too slow. I Don't want to include redis-namespace as a dependency because that's not my problem. If someone wants to use it vs redis then that's their decision.

**Comment by amoslanka** [comment]
That makes perfect sense to me.

**Pull request closed without merging**
