### PR TITLE
Feature/rails cache integration through dalli

### PR DESCRIPTION
**Pull request by KensoDev**

### CODE REVIEW

**Comment by KensoDev** [comment]
cc/ @Adman65

**Comment by ahawkins** [comment]
Can you please explain the uses cases and give me some examples?

**Comment by KensoDev** [comment]
sure.

You often don't cache things though the view, you cache it through the models, etc..

Often it looks something like this

``` ruby
Rails.cache.fetch("recommendations_#{place_id}") { Recommendation.where(place_id: place_id).all }
```

I want to bundle those together so I can remove all recommendations, so a tag is a perfect solution for that.

Another example

You have a leaderboard feature.

The leaderboard is cached using cache in the views, it's cached using the `Rails.cache.fetch` to get the leaderboard model.
When I invalidate, I don't want to bother about the keys, I want to invalidate the leaderboard in whole.

**Comment by KensoDev** [comment]
Sorry for the no description in the original pull, I completely forgot about it :-)

**Comment by KensoDev** [comment]
Don't pull yet please, I have some refactoring.

**Comment by KensoDev** [comment]
OK, now it's ready and good to go, tests green of course

**Comment by KensoDev** [comment]
Closed this one, I have a few more additions to the code. will open a pull request in a few, working on the README changes.

**Pull request closed without merging**
